name: game_counter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^4.0.1
  # Bloc for state managment
  bloc: ^5.0.0
  flutter_bloc: ^5.0.0
  # Value equality
  equatable: ^1.1.1
  # Functional programming
  dartz: ^0.8.9
  # Prebuilt material animations
  animations: ^1.0.0+5
  # Local Persistance
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  # Android-like android picker
  numberpicker: ^1.1.0
  # SnackBar on steroids
  flushbar: ^1.9.1
  # Annotations for freezed
  freezed_annotation: ^0.7.1
  flutter_material_color_picker: ^1.0.5
  # Date time format
  intl: ^0.16.1
  # Introduction screen
  introduction_screen: ^1.0.8
  

dependency_overrides:
  dartx: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  lint: ^1.1.1
  hive_generator: ^0.7.0+2
  build_runner: ^1.10.0
  bloc_test: ^6.0.0
  # Class code gen and Kotlin like when statement
  freezed: ^0.10.9


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
